import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsNotEmpty, IsOptional, IsString, Matches, MaxLength, MinLength } from 'class-validator';

export class SendOtpDto {
  @ApiPropertyOptional({
    example: 'WBPORTAL',
    description: 'Optional; defaults to WBPORTAL (citizen portal) for Option A identity.',
  })
  @IsOptional()
  @IsString()
  @MaxLength(20)
  tenant_code?: string;

  @ApiProperty({ example: '9876543210' })
  @IsString()
  @Matches(/^[6-9]\d{9}$/)
  mobile!: string;
}

export class VerifyOtpDto extends SendOtpDto {
  @ApiProperty({ minLength: 4, maxLength: 8, example: '123456' })
  @IsString()
  @MinLength(4)
  @MaxLength(8)
  otp!: string;
}

export class RefreshTokenDto {
  @ApiProperty()
  @IsString()
  @IsNotEmpty()
  refresh_token!: string;
}

export class LogoutDto {
  @ApiProperty()
  @IsString()
  @IsNotEmpty()
  refresh_token!: string;
}

export class AadhaarLinkDto {
  @ApiProperty({ description: 'DigiLocker authorization code returned to the citizen app.' })
  @IsString()
  @IsNotEmpty()
  code!: string;

  @ApiPropertyOptional({ description: 'OIDC state value generated by the citizen app.' })
  @IsOptional()
  @IsString()
  state?: string;
}

export interface OtpChallengeResponse {
  status: 'otp_requested';
  challenge_id: string;
  expires_in_seconds: number;
}

export interface TokenResponse {
  access_token: string;
  expires_in: number;
  refresh_expires_in?: number;
  refresh_token?: string;
  token_type: string;
  id_token?: string;
  scope?: string;
}
